package com.bac.tanahairku;

import java.util.ArrayList;

class DataProvinsi {
    private static String[][] dataProvinsi = {
            {"Aceh", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Coat_of_arms_of_Aceh.svg/1200px-Coat_of_arms_of_Aceh.svg.png", "Banda Aceh", "https://upload.wikimedia.org/wikipedia/commons/b/b2/Locator_Aceh_final.png", "Aceh adalah sebuah provinsi di Indonesia yang beribu kota Banda Aceh. Aceh merupakan salah satu provinsi di Indonesia yang diberi status sebagai daerah istimewa dan juga diberi kewenangan otonomi khusus. Aceh terletak di ujung utara pulau Sumatra dan merupakan provinsi paling barat di Indonesia. Jumlah penduduk provinsi ini sekitar 4.500.000 jiwa. Letaknya dekat dengan Kepulauan Andaman dan Nikobar di India dan terpisahkan oleh Laut Andaman. Aceh berbatasan dengan Teluk Benggala di sebelah utara, Samudra Hindia di sebelah barat, Selat Malaka di sebelah timur, dan Sumatra Utara di sebelah tenggara dan selatan. "},
            {"Bali", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Coat_of_arms_of_Bali.svg/1200px-Coat_of_arms_of_Bali.svg.png", "Denpasar", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Bali_in_Indonesia.svg/1200px-Bali_in_Indonesia.svg.png", "Bali adalah sebuah provinsi di Indonesia. Ibu kota provinsi ini adalah Denpasar. Bali juga merupakan salah satu pulau di Kepulauan Nusa Tenggara. Di awal kemerdekaan Indonesia, pulau ini termasuk dalam Provinsi Sunda Kecil yang beribu kota di Singaraja, dan kini terbagi menjadi 3 provinsi: Bali, Nusa Tenggara Barat, dan Nusa Tenggara Timur."},
            {"Banten", "https://upload.wikimedia.org/wikipedia/commons/8/82/Coat_of_arms_of_Banten.png", "Serang", "https://upload.wikimedia.org/wikipedia/commons/a/a8/IndonesiaBanten.png", "Banten (aksara Sunda: ᮘᮔ᮪ᮒᮨᮔ᮪ Hanacaraka: ꦨꦤ꧀ꦠꦼꦤ꧀; Pegon: بَنْتٓنْ）adalah sebuah provinsi di Tatar Pasundan, serta wilayah paling barat di Pulau Jawa, Indonesia. Provinsi ini pernah menjadi bagian dari Provinsi Jawa Barat, tetapi menjadi wilayah pemekaran sejak tahun 2000, dengan keputusan Undang-Undang Nomor 23 Tahun 2000. Pusat pemerintahannya berada di Kota Serang. "},
            {"Bengkulu", "https://upload.wikimedia.org/wikipedia/commons/7/7d/Coat_of_arms_of_Bengkulu.png", "Bengkulu", "https://upload.wikimedia.org/wikipedia/commons/9/99/Locator_bengkulu_final.png", "Bengkulu (bahasa Inggris: Bencoolen, Aks. Rejang: ꤷꥍꤲ꥓ꤰꥈꤾꥈ) adalah sebuah provinsi di Indonesia. Ibu kotanya berada di Kota Bengkulu. Provinsi ini terletak di bagian barat daya Pulau Sumatra. "},
            {"DKI Yogyakarta", "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Coat_of_arms_of_Yogyakarta.svg/1200px-Coat_of_arms_of_Yogyakarta.svg.png", "Yogyakarta", "https://upload.wikimedia.org/wikipedia/id/f/f2/Locator_yogya_final.png", "Daerah Istimewa Yogyakarta (bahasa Jawa: ꦝꦲꦺꦫꦃ​ꦆꦱ꧀ꦠꦶꦩꦺꦮ​ꦔꦪꦺꦴꦒꦾꦏꦂꦠ, translit. Dhaérah Istiméwa Ngayogyakarta) adalah Daerah Istimewa setingkat provinsi di Indonesia yang merupakan peleburan Negara Kesultanan Yogyakarta dan Negara Kadipaten Paku Alaman. Daerah Istimewa Yogyakarta terletak di bagian selatan Pulau Jawa, dan berbatasan dengan Provinsi Jawa Tengah dan Samudera Hindia. Daerah Istimewa yang memiliki luas 3.185,80 km2 ini terdiri atas satu kotamadya, dan empat kabupaten, yang terbagi lagi menjadi 78 kecamatan, dan 438 desa/kelurahan. Menurut sensus penduduk 2010 memiliki populasi 3.452.390 jiwa dengan proporsi 1.705.404 laki-laki, dan 1.746.986 perempuan, serta memiliki kepadatan penduduk sebesar 1.084 jiwa per km2."},
            {"DKI Jakarta", "https://2.bp.blogspot.com/-dR186qEfzPI/VwoNZkmb5WI/AAAAAAAAPF0/FMOz0VgOUPMqCCtwAjF35R631VRFtDNPg/s1600/Jakarta.png", "Jakarta", "https://upload.wikimedia.org/wikipedia/commons/c/cf/%D0%A0%D0%B0%D0%B9%D0%BE%D0%BD%D1%8B_%D0%98%D0%BD%D0%B4%D0%BE%D0%BD%D0%B5%D0%B7%D0%B8%D0%B8.png", "Daerah Khusus Ibukota Jakarta (DKI Jakarta) adalah ibu kota negara dan kota terbesar di Indonesia. Jakarta merupakan satu-satunya kota di Indonesia yang memiliki status setingkat provinsi. Jakarta terletak di pesisir bagian barat laut Pulau Jawa. Dahulu pernah dikenal dengan beberapa nama di antaranya Sunda Kelapa, Jayakarta, dan Batavia. Di dunia internasional Jakarta juga mempunyai julukan J-Town,[8] atau lebih populer lagi The Big Durian karena dianggap kota yang sebanding New York City (Big Apple) di Indonesia."},
            {"Gorontalo", "https://upload.wikimedia.org/wikipedia/commons/3/35/Lambang_propinsi_gorontalo.jpg", "Gorontalo", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Lambang_propinsi_gorontalo.jpg/180px-Lambang_propinsi_gorontalo.jpg", "Provinsi Gorontalo adalah salah satu Provinsi di Indonesia yang lahir pada tanggal 5 Desember, 2000[6] dan memiliki Ibu kota provinsi bernama sama yaitu, Kota Gorontalo. Sama halnya dengan ibu kotanya, Provinsi Gorontalo terkenal dengan julukan Serambi Madinah. Dalam catatan sejarah Indonesia, satu-satunya Presiden RI yang berasal dari Suku Gorontalo adalah Presiden Republik Indonesia ke-3, Prof. DR. Ing. B.J. Habibie, dari garis keturunan ayahnya yang memiliki marga Habibie, yaitu Alwi Abdul Jalil Habibie."},
            {"Jambi", "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Jambi_symbol.jpg/180px-Jambi_symbol.jpg", "Jambi", "https://upload.wikimedia.org/wikipedia/commons/0/0a/Locator_jambi.png", "Jambi (Jawi: جامبي) adalah sebuah Provinsi Indonesia yang terletak di pesisir timur di bagian tengah Pulau Sumatra. Jambi adalah satu dari tiga provinsi di Indonesia yang ibukotanya bernama sama dengan nama provinsinya, selain Bengkulu, Daerah Khusus Ibukota Jakarta, dan Gorontalo. "},
            {"Jawa Barat", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Coat_of_arms_of_West_Java.svg/100px-Coat_of_arms_of_West_Java.svg.png", "Bandung", "https://upload.wikimedia.org/wikipedia/id/thumb/d/df/Lokasi_Jawa_Barat_Indonesia.svg/250px-Lokasi_Jawa_Barat_Indonesia.svg.png", "Jawa Barat (disingkat Jabar) (Aksara Sunda Baku: ᮏᮝ ᮊᮥᮜᮧᮔ᮪, Sunda: Jawa Kulon, Carakan: ꦗꦮ​ꦏꦸꦭꦺꦴꦤ꧀, Cirebon: Jawa Kulon) adalah sebuah provinsi di Indonesia, ibu kotanya berada di Bandung. "},
            {"Jawa Tengah", "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Coat_of_arms_of_Central_Java.svg/100px-Coat_of_arms_of_Central_Java.svg.png", "Semarang", "https://upload.wikimedia.org/wikipedia/commons/2/2b/Locator_jateng_final.png", "Jawa Tengah (disingkat Jateng) (Hanacaraka: ꦗꦮ​ꦠꦼꦔꦃ; Jawa: Jåwå Tengah) adalah sebuah provinsi Indonesia yang terletak di bagian tengah Pulau Jawa. Ibu kotanya adalah Semarang. Provinsi ini berbatasan dengan Provinsi Jawa Barat di sebelah barat, Samudra Hindia dan Daerah Istimewa Yogyakarta di sebelah selatan, Jawa Timur di sebelah timur, dan Laut Jawa di sebelah utara. Luas wilayahnya 32.548 km², atau sekitar 28,94% dari luas pulau Jawa. Provinsi Jawa Tengah juga meliputi Pulau Nusakambangan di sebelah selatan (dekat dengan perbatasan Jawa Barat), serta Kepulauan Karimun Jawa di Laut Jawa. "},
            {"Jawa Timur", "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Coat_of_arms_of_East_Java.svg/100px-Coat_of_arms_of_East_Java.svg.png", "Surabaya", "https://upload.wikimedia.org/wikipedia/commons/b/ba/IndonesiaEastJava.png", "Jawa Timur (disingkat Jatim, bahasa Jawa: Hanacaraka: ꧋ꦗꦮꦮꦺꦠꦤ꧀ Pegon: جاوا ويتان, translit. Jåwå Wétan, bahasa Madura: Jhâbâh Dhimor) adalah sebuah provinsi di bagian timur Pulau Jawa, Indonesia. Ibu kotanya terletak di Surabaya. Luas wilayahnya 47.922 km², dan jumlah penduduknya 42.030.633 jiwa (sensus 2017). Jawa Timur memiliki wilayah terluas di antara 6 provinsi di Pulau Jawa, dan memiliki jumlah penduduk terbanyak kedua di Indonesia setelah Jawa Barat. Jawa Timur berbatasan dengan Laut Jawa di utara, Selat Bali di timur, Samudra Hindia di selatan, serta Provinsi Jawa Tengah di barat. Wilayah Jawa Timur juga meliputi Pulau Madura, Pulau Bawean, Pulau Kangean serta sejumlah pulau-pulau kecil di Laut Jawa (Kepulauan Masalembu), dan Samudera Hindia (Pulau Sempu, dan Nusa Barung). "},
            {"Kalimantan Barat", "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Coat_of_arms_of_West_Kalimantan.svg/335px-Coat_of_arms_of_West_Kalimantan.svg.png", "Pontianak", "https://upload.wikimedia.org/wikipedia/id/4/4b/Locator_kalbar_final.png", "Kalimantan Barat adalah sebuah provinsi di Indonesia yang terletak di Pulau Kalimantan dengan ibu kota Provinsi Kota Pontianak. Luas wilayah Provinsi Kalimantan Barat adalah 146.807 km². Merupakan provinsi terluas keempat setelah Papua, Kalimantan Timur dan Kalimantan Tengah."},
            {"Kalimantan Selatan", "https://upload.wikimedia.org/wikipedia/commons/7/71/Coat_of_arms_of_South_Kalimantan.gif", "Banjarmasin", "https://upload.wikimedia.org/wikipedia/commons/c/ce/Locator_kalsel_final.png", "Kalimantan Selatan (disingkat Kalsel) adalah salah satu provinsi di Indonesia yang terletak di pulau Kalimantan. Ibu kotanya adalah Banjarmasin. Provinsi Kalimantan Selatan memiliki luas 37.530,52 km²[14] dengan populasi hampir 4,2 juta jiwa (2019)"},
            {"Kalimantan Tengah", "https://upload.wikimedia.org/wikipedia/commons/e/eb/Coat_of_arms_of_Central_Kalimantan.png", "Palangkaraya", "https://upload.wikimedia.org/wikipedia/commons/d/da/IndonesiaCentralKalimantan.png", "Kalimantan Tengah (disingkat Kalteng) adalah salah satu provinsi di Indonesia yang terletak di Pulau Kalimantan. Ibu kotanya adalah Kota Palangkaraya. Kalimantan Tengah memiliki luas 153.564,60 km². Berdasarkan sensus tahun 2010, provinsi ini memiliki populasi 2.202.599 jiwa, yang terdiri atas 1.147.878 laki-laki dan 1.054.721 perempuan. Data BPS Kalimantan Tengah tahun 2019 menunjukkan penduduk provinsi ini tahun 2018 bertambah menjadi 2.660.209 (Laki-laki 1.391.078 jiwa dan perempuan 1.269.131 jiwa).[2] Kalimantan Tengah mempunyai 13 kabupaten dan 1 kota."},
            {"Kalimantan Timur", "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Coat_of_arms_of_East_Kalimantan.svg/490px-Coat_of_arms_of_East_Kalimantan.svg.png", "Samarinda", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/East_Kalimantan_in_Indonesia.svg/800px-East_Kalimantan_in_Indonesia.svg.png", "Kalimantan Timur adalah sebuah provinsi Indonesia di Pulau Kalimantan bagian ujung timur yang berbatasan dengan Malaysia, Kalimantan Utara, Kalimantan Tengah, Kalimantan Selatan, Kalimantan Barat, dan Sulawesi. Luas total Kaltim adalah 127.346,92 km² dan populasi sebesar 3.575.449 jiwa."},
            {"Kalimantan Utara", "https://upload.wikimedia.org/wikipedia/commons/3/33/Emblem_of_North_Kalimantan.png", "Tanjung Selor", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/North_Kalimantan_in_Indonesia.svg/800px-North_Kalimantan_in_Indonesia.svg.png", "Kalimantan Utara adalah sebuah provinsi di Indonesia yang terletak di bagian utara Pulau Kalimantan. Provinsi ini berbatasan langsung dengan negara tetangga Malaysia, yaitu Negara Bagian Sabah dan Sarawak"},
            {"Kepulauan Bangka Belitung", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Coat_of_arms_of_Bangka_Belitung_Islands.svg/335px-Coat_of_arms_of_Bangka_Belitung_Islands.svg.png", "Pangkal Pinang", "https://upload.wikimedia.org/wikipedia/commons/2/20/Locator_babel_final.png", "Provinsi Kepulauan Bangka Belitung adalah sebuah provinsi di Indonesia yang terdiri dari dua pulau utama yaitu Pulau Bangka dan Pulau Belitung serta ratusan pulau-pulau kecil, total pulau yang telah bernama berjumlah 470 buah dan yang berpenghuni hanya 50 pulau."},
            {"Kepulauan Riau", "https://upload.wikimedia.org/wikipedia/commons/e/ee/Coat_of_arms_of_Riau_Islands.png", "Tanjung Pinang", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Indonesia_Riau_Islands_location_map.svg/600px-Indonesia_Riau_Islands_location_map.svg.png", "Kepulauan Riau adalah sebuah provinsi di Indonesia. Provinsi Kepulauan Riau berbatasan dengan Vietnam dan Kamboja di sebelah utara; Malaysia dan provinsi Kalimantan Barat di timur; provinsi Kepulauan Bangka Belitung dan Jambi di selatan; Negara Singapura, Malaysia dan provinsi Riau di sebelah barat."},
            {"Lampung", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Coat_of_arms_of_Lampung.svg/289px-Coat_of_arms_of_Lampung.svg.png", "Bandar Lampung", "https://upload.wikimedia.org/wikipedia/commons/b/b6/Locator_lampung_final.png", "Lampung (Aksara Lampung: ) adalah sebuah provinsi paling selatan di Pulau Sumatra, Indonesia, dengan ibu kota Bandar Lampung. Provinsi ini memiliki dua kota yaitu Kota Bandar Lampung, Kota Metro, dan Kota Pringsewu serta 12 kabupaten. Posisi Lampung secara geografis berada di sebelah barat berbatasan dengan Samudra Hindia, di sebelah timur dengan Laut Jawa, di sebelah utara berbatasan dengan provinsi Sumatra Selatan, dan di sebelah selatan berbatasan dengan Selat Sunda."},
            {"Maluku", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Coat_of_arms_of_Maluku.svg/243px-Coat_of_arms_of_Maluku.svg.png", "Ambon", "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Maluku_in_Indonesia.svg/800px-Maluku_in_Indonesia.svg.png", "Maluku adalah sebuah provinsi yang meliputi bagian selatan Kepulauan Maluku, Indonesia. Provinsi ini berbatasan dengan Laut Seram di utara, Samudra Hindia dan Laut Arafura di selatan, Papua di timur, dan Sulawesi di barat. Ibu kota dan kota terbesarnya ialah Ambon. "},
            {"Maluku Utara", "https://upload.wikimedia.org/wikipedia/commons/b/b9/Coat_of_arms_of_North_Maluku.png", "Ternate", "https://upload.wikimedia.org/wikipedia/id/2/2a/Locator_malut_final.png", "Maluku Utara adalah salah satu provinsi di Indonesia. Maluku Utara resmi terbentuk pada tanggal 4 Oktober 1999, melalui UU RI Nomor 46 Tahun 1999 dan UU RI Nomor 6 Tahun 2003."},
            {"Nusa Tenggara Barat", "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Coat_of_arms_of_West_Nusa_Tenggara.svg/335px-Coat_of_arms_of_West_Nusa_Tenggara.svg.png", "Mataram", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/West_Nusa_Tenggara_in_Indonesia.svg/800px-West_Nusa_Tenggara_in_Indonesia.svg.png", "Nusa Tenggara Barat ialah sebuah provinsi di Indonesia yang berada pada bagian barat Kepulauan Nusa Tenggara. Provinsi ini beribu kota di Mataram dan memiliki 10 Kabupaten dan Kota. Pada awal kemerdekaan Indonesia, wilayah ini termasuk dalam wilayah Provinsi Sunda Kecil yang beribu kota di Singaraja. "},
            {"Nusa Tenggara Timur", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Coat_of_arms_of_East_Nusa_Tenggara.svg/487px-Coat_of_arms_of_East_Nusa_Tenggara.svg.png", "Kupang", "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/East_Nusa_Tenggara_in_Indonesia.svg/800px-East_Nusa_Tenggara_in_Indonesia.svg.png", "Nusa Tenggara Timur adalah sebuah provinsi di Indonesia yang meliputi bagian timur Kepulauan Nusa Tenggara. Provinsi ini beribu kota di Kupang dan memiliki 22 kabupaten/kota. Provinsi ini berada di Sunda Kecil."},
            {"Papua", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Coat_of_arms_of_Papua.svg/432px-Coat_of_arms_of_Papua.svg.png", "Jayapura", "https://upload.wikimedia.org/wikipedia/commons/d/d6/Locator_papua_final.png", "Papua adalah provinsi terluas Indonesia yang terletak di bagian tengah Pulau Papua atau bagian paling timur wilayah Papua milik Indonesia. Belahan timurnya merupakan negara Papua Nugini. Provinsi Papua sebelumnya bernama Irian Jaya yang mencakup seluruh wilayah Papua Bagian barat."},
            {"Papua Barat", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Coat_of_arms_of_West_Papua.svg/365px-Coat_of_arms_of_West_Papua.svg.png", "Manokwari", "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/West_Papua_in_Indonesia.svg/800px-West_Papua_in_Indonesia.svg.png", "Papua Barat adalah sebuah provinsi Indonesia yang terletak di ujung barat Pulau Papua. Ibu kotanya adalah Manokwari. Nama provinsi ini sebelumnya adalah Irian Jaya Barat yang ditetapkan dalam Undang-Undang Nomor 45 Tahun 1999. "},
            {"Riau", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Coat_of_arms_of_Riau.svg/335px-Coat_of_arms_of_Riau.svg.png", "Pekanbaru", "https://upload.wikimedia.org/wikipedia/commons/1/1d/IndonesiaRiau.png", "Riau adalah sebuah provinsi di Indonesia yang terletak di bagian tengah pulau Sumatra. Provinsi ini terletak di bagian tengah pantai timur Pulau Sumatra, yaitu di sepanjang pesisir Selat Melaka."},
            {"Sulawesi Barat", "https://upload.wikimedia.org/wikipedia/commons/8/81/Coat_of_arms_of_West_Sulawesi.png", "Mamuju", "https://upload.wikimedia.org/wikipedia/commons/c/cc/Locator_sulbar_final.png", "Sulawesi Barat adalah sebuah provinsi di Indonesia yang terletak di bagian barat Sulawesi. Pembentukan Provinsi Sulawesi Barat telah diperjuangkan sejak tahun 1960. Pada masa itu pulau Sulawesi terdapat 3 Provinsi yakni Provinsi Sulawesi Selatan, Provinsi Sulawesi Tengah dan Provinsi Sulawesi Utara."},
            {"Sulawesi Selatan", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Coat_of_arms_of_South_Sulawesi.svg/349px-Coat_of_arms_of_South_Sulawesi.svg.png", "Makassar", "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/South_Sulawesi_in_Indonesia.svg/800px-South_Sulawesi_in_Indonesia.svg.png", "Sulawesi Selatan (disingkat Sulsel) (Lontara: ᨔᨘᨒᨓᨙᨔᨗ ᨔᨒᨈ ) adalah sebuah provinsi di Indonesia yang terletak di bagian selatan Sulawesi. Ibu kotanya adalah Makassar."},
            {"Sulawesi Tengah", "https://upload.wikimedia.org/wikipedia/commons/b/bf/Coat_of_arms_of_Central_Sulawesi.png", "Palu", "https://upload.wikimedia.org/wikipedia/commons/6/66/Locator_sulteng_final.png", "Sulawesi Tengah adalah sebuah provinsi di bagian tengah Pulau Sulawesi, Indonesia. Ibu kota provinsi ini adalah Kota Palu. Luas wilayahnya 61.841,29 km², dan jumlah penduduknya 3.222.241 jiwa."},
            {"Sulawesi Tenggara", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Coat_of_arms_of_Southeast_Sulawesi.svg/444px-Coat_of_arms_of_Southeast_Sulawesi.svg.png", "Kendari", "https://upload.wikimedia.org/wikipedia/commons/6/68/Locator_sultra_final.png", "Sulawesi Tenggara merupakan sebuah provinsi di Indonesia yang terletak bagian tenggara pulau Sulawesi dengan ibu kota Kendari. "},
            {"Sulawesi Utara", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Coat_of_arms_of_North_Sulawesi.svg/335px-Coat_of_arms_of_North_Sulawesi.svg.png", "Manado", "https://upload.wikimedia.org/wikipedia/commons/f/f1/Locator_sulut_final.png", "Sulawesi Utara adalah salah satu provinsi yang terletak di ujung utara Pulau Sulawesi dengan ibu kota terletak di kota Manado."},
            {"Sumatera Barat", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Coat_of_arms_of_West_Sumatra.svg/443px-Coat_of_arms_of_West_Sumatra.svg.png", "Padang", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/West_Sumatra_in_Indonesia.svg/800px-West_Sumatra_in_Indonesia.svg.png", "Sumatra Barat adalah sebuah provinsi di Indonesia yang terletak di Pulau Sumatra dengan Padang sebagai ibu kotanya. Provinsi Sumatra Barat terletak sepanjang pesisir barat Sumatra bagian tengah, dataran tinggi Bukit Barisan di sebelah timur, dan sejumlah pulau di lepas pantainya seperti Kepulauan Mentawai."},
            {"Sumatera Selatan", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Coat_of_arms_of_South_Sumatra.svg/394px-Coat_of_arms_of_South_Sumatra.svg.png", "Palembang", "https://upload.wikimedia.org/wikipedia/commons/e/ef/Locator_sumsel_final.png", "Sumatra Selatan adalah provinsi di Indonesia yang terletak di bagian selatan Pulau Sumatra. Provinsi ini beribu kota di Palembang. Secara geografis, Sumatra Selatan berbatasan dengan provinsi Jambi di utara, provinsi Kep. Bangka-Belitung di timur, provinsi Lampung di selatan dan Provinsi Bengkulu di barat."},
            {"Sumatera Utara", "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Coat_of_arms_of_North_Sumatra.svg/360px-Coat_of_arms_of_North_Sumatra.svg.png", "Medan", "https://upload.wikimedia.org/wikipedia/commons/9/9b/Locator_north_sumatra.png", "Sumatra Utara adalah sebuah provinsi di Indonesia yang terletak di bagian utara Pulau Sumatra. Provinsi ini beribu kota di Medan. Luas wilayahnya 72.981 km²."}
    };


    static ArrayList<Provinsi> getListProvinsi() {
        ArrayList<Provinsi> list = new ArrayList<>();
        for (String[] d : dataProvinsi) {
            Provinsi provinsi = new Provinsi();
            provinsi.setName(d[0]);
            provinsi.setLambang(d[1]);
            provinsi.setIbukota(d[2]);
            provinsi.setWilayah(d[3]);
            provinsi.setDescription(d[4]);
            list.add(provinsi);
        }
        return list;
    }

}
